/*
 * @Author       : jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2025-12-17 12:47:50
 * @LastAuthor   : jry
 * @lastTime     : 2025-12-17 12:47:50
 * @FilePath     : /uview-ultra/libs/config/props/lazyLoad.uts
 */
export default {
	// lazyLoad组件
	lazyLoad: {
		index: '',
		image: '',
		imgMode: 'widthFix',
		loadingImg: ''
		errorImg: ''
	}
} as UTSJSONObject
