/*
 * @Author       : jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2025-11-06 12:20:08
 * @LastAuthor   : jry
 * @lastTime     : 2025-11-06 12:20:08
 * @FilePath     : /uview-ultra/libs/config/props/countDown
 */
export default {
    // count-down 计时器组件
    countDown: {
        time: 0,
        format: 'HH:mm:ss',
        autoStart: true,
        millisecond: false
    }
} as UTSJSONObject
